// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWuhwcdYu8RARIUW_wzYs-Qeh28Xla_mE',
    appId: '1:145970934590:web:501f7421970cd53014b26f',
    messagingSenderId: '145970934590',
    projectId: 'refrigerator-management-60c55',
    authDomain: 'refrigerator-management-60c55.firebaseapp.com',
    storageBucket: 'refrigerator-management-60c55.firebasestorage.app',
    measurementId: 'G-BJ034KTEEW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgCl6nQzwO8CefYmiD-lVBmhc3sRH-i6s',
    appId: '1:145970934590:android:a957d835d25374f014b26f',
    messagingSenderId: '145970934590',
    projectId: 'refrigerator-management-60c55',
    storageBucket: 'refrigerator-management-60c55.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA49IFcZi27dlzoWUyFt-LAPRB8zHE0e7w',
    appId: '1:145970934590:ios:0c1b74d36c2dc67714b26f',
    messagingSenderId: '145970934590',
    projectId: 'refrigerator-management-60c55',
    storageBucket: 'refrigerator-management-60c55.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA49IFcZi27dlzoWUyFt-LAPRB8zHE0e7w',
    appId: '1:145970934590:ios:0c1b74d36c2dc67714b26f',
    messagingSenderId: '145970934590',
    projectId: 'refrigerator-management-60c55',
    storageBucket: 'refrigerator-management-60c55.firebasestorage.app',
    iosBundleId: 'com.example.myApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWuhwcdYu8RARIUW_wzYs-Qeh28Xla_mE',
    appId: '1:145970934590:web:4ed420678bf41b3b14b26f',
    messagingSenderId: '145970934590',
    projectId: 'refrigerator-management-60c55',
    authDomain: 'refrigerator-management-60c55.firebaseapp.com',
    storageBucket: 'refrigerator-management-60c55.firebasestorage.app',
    measurementId: 'G-MELDWBSJ0H',
  );

}